### ISSUE TITLE
Missing artifact ficus_2.10

### ISSUE THREAD

**Issue by tsukaby** [iheartradio/ficus#20]
I have been using the Scala 2.10.6 with Apache Spark 1.6.1. (Official Apache Spark binary depend to Scala 2.10.x)

I want to the ficus on Scala 2.10.

```
// for Scala 2.10.x
libraryDependencies += "com.iheart" %% "ficus" % "1.0.2"
```

But I can't find files.

![https___jcenter_bintray_com_com_iheart_](https://cloud.githubusercontent.com/assets/6133458/15172545/a8f221da-1791-11e6-9faa-26a2a55c074c.png)

Can you help me?
Thank you great developers!

**Comment by joprice** [comment]
We're not currently cross publishing. We can look into supporting this.

**Comment by tsukaby** [comment]
@joprice Thank you!

**Comment by 1ambda** [comment]
For someone who are facing the same issue,

Add `Resolver.bintrayRepo("iheartradio", "maven")` to your sbt file
