### ISSUE TITLE
"com.iheart" %% "ficus" % "1.0.2" is not published!

### ISSUE THREAD

**Issue by mayhemm** [iheartradio/ficus#31]
"com.iheart" %% "ficus" % "1.0.2" gives an 404.

Can you please publish it?

Thanks

**Comment by kailuowang** [comment]
It's published [here](https://bintray.com/iheartradio/maven/ficus/1.0.2). You might need to add bintray jcenter as a resolver as `resolvers += Resolver.jcenterRepo`

**Comment by mayhemm** [comment]
Build.sbt:

resolvers += Resolver.jcenterRepo

libraryDependencies ++= Seq(
  "com.typesafe" % "config" % "1.3.0",
  //"net.ceedubs" %% "ficus" % "1.0.1",
  "com.iheart" %%  "ficus" % "1.0.2"
)

SBT output:
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/com/iheart/ficus_2.10/1.0.2/ficus_2.10-1.0.2.pom

That jcender url throws an 404.

**Comment by mayhemm** [comment]
Ok got it working.

Use this one: resolvers += Resolver.bintrayRepo("iheartradio", "maven")

**Comment by kailuowang** [comment]
Cool, thanks for reporting. I don't understand how come that version didn't get linked in jcenter. Might be a sbt jcenterRepo bug? What sbt version are you on? Anyway I am glad you resolved the issue.

**Comment by mayhemm** [comment]
SBT 0.13.12.
