### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by leonardehrenfried** [iheartradio/ficus#32]
I know that this is a little complicated but it would be great to have this on Maven Central.

I've done that before and can help out if you want.

**Comment by kailuowang** [comment]
Would love to get some help on this one. Thanks!

**Comment by leonardehrenfried** [comment]
I opened PR #34 which adds a bit of code that enables you to upload to Maven Central. Unfortunately there is a bit of work for you to do but I've detailed it in the PR description.

**Comment by kailuowang** [comment]
Phished, and thanks for the contribution!
