### ISSUE TITLE
Artifacts for Scala 2.12 not found in jCenter

### ISSUE THREAD

**Issue by augi** [iheartradio/ficus#42]
The artifacts for Scala 2.12 are not available in [Bintray](https://jcenter.bintray.com/com/iheart/) :( 

According to [this blog post](https://protyposis.net/blog/how-including-a-bintray-maven-repository-in-jcenter-works-under-the-hood/) it seems that you should recreate the package in Bintray so the _filter_ will include also the new files.

**Comment by kailuowang** [comment]
To be more precise it's on bintray but not available through jCenter. 
I'll try the approach suggested in the link. 
Meanwhile here is a work around
```
resolvers +=  Resolver.bintrayRepo("iheartradio","maven")

```

**Comment by augi** [comment]
Yep, it's not correctly available in jCenter. I will wait for the proper fix instead of adding a new repo into the project :) Thanks!

**Comment by kailuowang** [comment]
We just published 1.3.4 to maven central with support for all 3 scala versions
